# -*- coding: utf-8 -*-
"""Final Project: Data Wrangling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bp-nyHMczo9DGJOS-qavjHddVoj7PYXS
"""

import pandas as pd
import numpy as np

######  1  ########

cd=pd.read_csv("https://raw.githubusercontent.com/SR1608/Datasets/main/covid-data.csv")

######  2  ########

# A.
print(
    ' no of columns: ',len(cd.columns),'\n',
    'no of rows: ',len(cd)
)

# B.
cd.dtypes

#C. 
cd.info(show_counts=True)

cd.describe(include='all')

######  3  ########

# A.
len(cd['location'].unique())

# B.
cd['continent'].mode()

# C.
print(
    ' maximum in total deaths:',cd['total_deaths'].max(),'\n',
    'mean in total deaths:',cd['total_deaths'].mean()
)

# D.
cd['total_deaths'].quantile([0.25,0.5,0.75])

# E.
set(list(cd['continent'][cd['human_development_index']==cd['human_development_index'].max()]))

# F.
set(list(cd['continent'][cd['gdp_per_capita']==cd['gdp_per_capita'].min()]))

######  4  ########

cd=cd[['continent','location','date','total_cases','total_deaths','gdp_per_capita','human_development_index']]

######  5  ########

# A.
cd.drop_duplicates(inplace=True)

# B.
cd.isna().sum()

# C.
cd=cd[cd['continent'].notna()]

cd.fillna(0,inplace=True)

######  6  ########

# A.
cd['date']=pd.to_datetime(cd['date'])

# B.
cd['month']=cd['date'].dt.month

######  7  ########

# A.
cd.groupby('continent').max()

# B.
df_groupby=cd.groupby('continent').max()

######    ########

df_groupby['total_deaths_to_total_cases']=df_groupby['total_deaths']/df_groupby['total_cases']

######  9  ########

import seaborn as sns

# A.
sns.distplot(df_groupby['gdp_per_capita'])

# B.
sns.scatterplot(df_groupby['total_cases'],df_groupby['gdp_per_capita'])

# C.
sns.pairplot(df_groupby)

# D.
sns.barplot(df_groupby['total_cases'],df_groupby.index)

######  10  ########

df_groupby.to_csv('coviddata.csv')